name: robotforge-python-sdk

on:
  push:
    branches: 
      - staging
  release:
    types: [published]

jobs:
  build-dists:
    name: Build distribution
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build
      - name: Build package
        run: |
          python -m build
      - name: Store distributions
        uses: actions/upload-artifact@v4
        with:
          name: python-distributions
          path: dist/

  publish-test:
    name: Publish to TestPyPI
    needs: [build-dists]
    if: |
      github.event_name == 'release' && 
      github.event.action == 'published' && 
      github.event.release.target_commitish == 'staging'
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/robotforge-python-sdk/
    permissions:
      id-token: write
    steps:
      - name: Retrieve distributions
        uses: actions/download-artifact@v4
        with:
          name: python-distributions
          path: dist/
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    name: Publish release to PyPI
    needs: [build-dists]
    if: |
      github.event_name == 'release' && 
      github.event.action == 'published' && 
      github.event.release.target_commitish == 'main' 
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/robotforge-python-sdk/
    permissions:
      id-token: write
    steps:
      - name: Retrieve distributions
        uses: actions/download-artifact@v4
        with:
          name: python-distributions
          path: dist/
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1